name: sigev
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  image_picker: ^1.2.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.1
  page_animation_transition: ^1.0.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  toastification: ^3.0.3
  provider: ^6.1.5+1
  camera: ^0.11.3
  photo_manager: ^3.8.2
  get_it: ^9.1.1
  flutter_localization: ^0.3.3
  go_router: ^17.0.0
  dotted_border: ^3.1.0
  file_picker: ^10.3.7
  pdfx: ^2.9.2
  flutter_date_pickers: ^0.4.3
  cunning_document_scanner: ^1.4.0
  easy_image_viewer: ^1.5.1
  keyboard_actions: ^4.2.1
  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: chivo
      fonts:
        - asset: fonts/Chivo-Black.ttf
        - asset: fonts/Chivo-Bold.ttf
        - asset: fonts/Chivo-ExtraBold.ttf
        - asset: fonts/Chivo-ExtraLight.ttf
        - asset: fonts/Chivo-Light.ttf
        - asset: fonts/Chivo-LightItalic.ttf
        - asset: fonts/Chivo-Medium.ttf
        - asset: fonts/Chivo-MediumItalic.ttf
        - asset: fonts/Chivo-Regular.ttf
        - asset: fonts/Chivo-Thin.ttf
    - family: manrope
      fonts:
        - asset: fonts/Manrope-Bold.ttf
        - asset: fonts/Manrope-ExtraBold.ttf
        - asset: fonts/Manrope-ExtraLight.ttf
        - asset: fonts/Manrope-Light.ttf
        - asset: fonts/Manrope-Medium.ttf
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-SemiBold.ttf
    - family: IconsOwn 
      fonts:
        - asset: fonts/IconsOwn.ttf
    - family: IconsBarProgress 
      fonts:
        - asset: fonts/IconsBarProgress.ttf
flutter_icons:
  android: true
  ios: true
  image_path_android: "images/logo_sighev.png"
  adaptive_icon_background: "#0A8B8F"
  adaptive_icon_foreground: "images/logo_sighev.png"
  image_path_ios: "images/logo_sighev.png"
  remove_alpha_ios: true